### ISSUE TITLE
ValueError: Object arrays cannot be loaded when allow_pickle=False

### ISSUE THREAD

**Issue by Th0rgal** [jkrauze/ntru#3]
Hello,

I just cloned the repository but when I tried the examples in the doc, for example:
```
python ./ntru.py enc ./myKey.pub.npz ./test.txt
```
Here is the output:
```
Traceback (most recent call last):
  File "./ntru.py", line 149, in <module>
    output = encrypt(args['PUB_KEY_FILE'], input_arr, bin_output=not poly_output, block=block)
  File "./ntru.py", line 55, in encrypt
    ntru.h_poly = Poly(pub_key['h'].astype(np.int)[::-1], x).set_domain(ZZ)
  File "/nix/store/vvlzfcwnsdjacv0fq7vg7rchmskj5d96-python3-3.7.5-env/lib/python3.7/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/nix/store/vvlzfcwnsdjacv0fq7vg7rchmskj5d96-python3-3.7.5-env/lib/python3.7/site-packages/numpy/lib/format.py", line 722, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```

I'm using python 3.7.5 on nixos (linux 5.4.8).

Thank you!

**Comment by jkrauze** [comment]
Hello,

This error is related to some security fixes in NumPy package (you can read more here: https://github.com/numpy/numpy/issues/12759).

I've just changed all `np.load()` calls to use `allow_pickle=True`, it should be working fine now.
