### ISSUE TITLE
Error while decryption

### ISSUE THREAD

**Issue by shabbir-darbar** [jkrauze/ntru#5]
Generated keys with following parameters 
N = 251, p = 3, q = 128

input file 'pt.txt' contains text "hello"

encryption operation works without errors to generate output which is stored in output file with the following command:
python .\ntru.py enc -b .\myKey.pub.npz .\pt.txt > ct.txt

The code gives the following error while decrypting with the following command:
python .\ntru.py dec -b .\myKey.priv.npz .\ct.txt

Error:
Traceback (most recent call last):
  File ".\ntru.py", line 151, in <module>
    output = decrypt(args['PRIV_KEY_FILE'], input_arr, bin_input=not poly_input, block=block)
  File ".\ntru.py", line 99, in decrypt
    input_arr = input_arr.reshape((-1, ntru.N))
ValueError: cannot reshape array of size 1016 into shape (251)

**Comment by shabbir-darbar** [comment]
I was working on the windows power shell terminal. However, when I tried the code using an Ubuntu terminal, the code worked correctly. The above issue was likely due to powershell. Reason for the issue in powershell terminal is still unclear.
